import urllib.request
import json
import sys

def main():
    url = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
    print("Fetching emoji database...")
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode('utf-8'))
    except Exception as e:
        print(f"Error fetching data: {e}", file=sys.stderr)
        sys.exit(1)
        
    print(f"Loaded {len(data)} emojis. Generating EmojiData.swift...")
    
    swift_code = []
    swift_code.append("// This file is autogenerated by generate_emoji_data.py. Do not edit manually.\n")
    swift_code.append("import Foundation\n")
    swift_code.append("struct Emoji: Codable, Identifiable, Hashable {")
    swift_code.append("    var id: String { emoji }")
    swift_code.append("    let emoji: String")
    swift_code.append("    let description: String")
    swift_code.append("    let category: String")
    swift_code.append("    let aliases: [String]")
    swift_code.append("    let tags: [String]")
    swift_code.append("}\n")
    swift_code.append("let allEmojis: [Emoji] = [")
    
    for entry in data:
        emoji = entry.get("emoji", "")
        description = entry.get("description", "").replace('"', '\\"')
        category = entry.get("category", "").replace('"', '\\"')
        aliases = entry.get("aliases", [])
        tags = entry.get("tags", [])
        
        aliases_str = "[" + ", ".join(f'"{a.replace("\"", "\\\"")}"' for a in aliases) + "]"
        tags_str = "[" + ", ".join(f'"{t.replace("\"", "\\\"")}"' for t in tags) + "]"
        
        swift_code.append(f'    Emoji(emoji: "{emoji}", description: "{description}", category: "{category}", aliases: {aliases_str}, tags: {tags_str}),')
        
    # Remove the trailing comma from the last element if we have elements
    if len(data) > 0:
        swift_code[-1] = swift_code[-1][:-1]
        
    swift_code.append("]")
    
    with open("EmojiData.swift", "w", encoding="utf-8") as f:
        f.write("\n".join(swift_code))
        
    print("EmojiData.swift generated successfully!")

if __name__ == "__main__":
    main()
